import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Share2,
  CheckCircle2,
  AlertTriangle,
  Info,
  ArrowLeft,
  ShieldCheck,
  Calendar,
  Sparkles,
  Printer
} from 'lucide-react';
import jsPDF from 'jspdf';
import { reportApi } from '../services/api';
import { HealthReport } from '../types';

interface Props {
  onBack: () => void;
}

export const ReportsScreen: React.FC<Props> = ({ onBack }) => {
  const [report, setReport] = useState<HealthReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    try {
      const res = await reportApi.getLatest();
      setReport(res.report);
    } catch (e) {
      console.warn('Failed to load report', e);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadPdf = () => {
    if (!report) return;
    setIsGeneratingPdf(true);
    setPdfError(null);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // Colors
      const primaryGreen = [21, 128, 61]; // #15803D
      const darkText = [31, 36, 33];
      const grayText = [107, 114, 128];

      // Header Banner
      doc.setFillColor(21, 128, 61);
      doc.rect(0, 0, 210, 24, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('SwasthAI - Personal Health Screening Report', 14, 15);

      // Metadata
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Patient: ${report.userName} | Age: ${report.age} | Sex: ${report.sex}`, 14, 32);
      doc.text(`Generated: ${new Date(report.createdAt).toLocaleString()} | Report ID: ${report.id}`, 14, 38);

      // Disclaimer Box
      doc.setDrawColor(245, 158, 11);
      doc.setFillColor(254, 243, 199);
      doc.roundedRect(14, 43, 182, 14, 2, 2, 'FD');
      doc.setFontSize(8);
      doc.setTextColor(146, 64, 14);
      doc.text(
        'CLINICAL NOTICE: This report is generated by a non-invasive smartphone screening system. It provides physiological',
        17,
        48
      );
      doc.text(
        'monitoring and trend analysis. It is NOT a clinical diagnosis or medical device certification.',
        17,
        53
      );

      // Executive Summary
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      doc.text('1. Executive Screening Assessment', 14, 65);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Overall Status: ${report.overallStatus.toUpperCase()}`, 14, 71);
      doc.text(`Confidence Score: ${report.confidenceScore}%`, 14, 76);
      const splitSummary = doc.splitTextToSize(report.executiveSummary, 182);
      doc.text(splitSummary, 14, 82);

      // Measured Vital Signs Table
      let y = 98;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('2. Quantitative Vital Signs & Sensor Screening', 14, y);

      y += 6;
      doc.setFillColor(243, 244, 246);
      doc.rect(14, y, 182, 7, 'F');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('PARAMETER', 17, y + 5);
      doc.text('RECORDED VALUE', 85, y + 5);
      doc.text('SCREENING STATUS', 145, y + 5);

      y += 7;
      doc.setFont('helvetica', 'normal');
      const tableRows = (report.modules && report.modules.length > 0)
        ? report.modules.map(m => [
            m.name.length > 34 ? m.name.substring(0, 34) + '...' : m.name,
            m.tested ? m.valueDisplay : 'Not Tested',
            m.tested ? (m.healthStatus ? m.healthStatus.toUpperCase() : 'NORMAL') : 'NOT TESTED'
          ])
        : [
            ['Resting Heart Rate (PPG)', report.vitals.heartRate !== null && report.vitals.heartRate !== undefined ? `${report.vitals.heartRate} BPM` : 'Not Tested', report.vitals.heartRateStatus ? report.vitals.heartRateStatus.toUpperCase() : 'NOT_TESTED'],
            ['Heart Rate Variability (RMSSD)', report.vitals.hrvRmssd !== null && report.vitals.hrvRmssd !== undefined ? `${report.vitals.hrvRmssd} ms` : 'Not Tested', report.vitals.hrvStatus ? report.vitals.hrvStatus.toUpperCase() : 'NOT_TESTED'],
            ['Estimated SpO2 (Prototype Proxy)', report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? `~${report.vitals.estimatedSpO2}%` : 'Not Tested', report.vitals.estimatedSpO2 !== null ? 'EXPERIMENTAL' : 'NOT_TESTED'],
            ['Weight / Body Mass Index', report.vitals.bmi !== null && report.vitals.bmi !== undefined ? `${report.vitals.weightKg} kg (BMI: ${report.vitals.bmi})` : 'Not Tested', report.vitals.bmi !== null ? 'NORMAL' : 'NOT_TESTED'],
            ['Walking Cadence (Gait)', report.vitals.cadence !== null && report.vitals.cadence !== undefined ? `${report.vitals.cadence} steps/min` : 'Not Tested', report.vitals.gaitStatus ? report.vitals.gaitStatus.toUpperCase() : 'NOT_TESTED'],
            ['Acoustic Heart Sound Rhythm', report.vitals.heartSoundPattern ? report.vitals.heartSoundPattern.replace(/_/g, ' ') : 'Not Tested', report.vitals.heartSoundStatus ? report.vitals.heartSoundStatus.toUpperCase() : 'NOT_TESTED'],
            ['Acoustic Respiratory / Cough', report.vitals.coughPattern ? report.vitals.coughPattern.replace(/_/g, ' ') : 'Not Tested', report.vitals.coughStatus ? report.vitals.coughStatus.toUpperCase() : 'NOT_TESTED']
          ];

      tableRows.forEach(row => {
        doc.text(row[0], 17, y + 5);
        doc.text(row[1], 85, y + 5);
        doc.text(row[2], 145, y + 5);
        doc.setDrawColor(229, 231, 235);
        doc.line(14, y + 7, 196, y + 7);
        y += 7;
      });

      // Clinical Action Items
      y += 6;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('3. Physician Discussion Recommendations', 14, y);

      y += 6;
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      report.actionItems.forEach(item => {
        doc.text(`• ${item}`, 17, y);
        y += 5;
      });

      // Save PDF file
      doc.save(`SwasthAI_Health_Report_${report.id}.pdf`);
    } catch (err: any) {
      console.error(err);
      setPdfError(err.message || 'Unable to generate PDF report in this browser environment.');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  if (isLoading || !report) {
    return (
      <div className="mx-auto max-w-lg p-8 text-center text-xs text-gray-500">
        Loading latest health assessment report...
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-lg space-y-4 p-4 pb-24 animate-fade-in">
      {pdfError && (
        <div className="rounded-xl bg-red-50 p-2.5 text-xs text-red-700 border border-red-200">
          {pdfError}
        </div>
      )}

      {/* Top Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={onBack}
          className="flex items-center gap-1 text-xs font-semibold text-gray-600 hover:text-gray-900"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back</span>
        </button>

        <button
          onClick={downloadPdf}
          disabled={isGeneratingPdf}
          className="flex items-center gap-1.5 rounded-xl bg-[#15803D] px-3.5 py-1.5 text-xs font-bold text-white shadow hover:bg-[#166534] transition-all disabled:opacity-50"
        >
          <Download className="h-3.5 w-3.5" />
          <span>{isGeneratingPdf ? 'Exporting...' : 'Download PDF'}</span>
        </button>
      </div>

      {/* Structured Health Report Preview */}
      <div className="rounded-3xl border border-[#EAE7DE] bg-white p-6 shadow-xs space-y-5">
        {/* Document Header */}
        <div className="border-b border-gray-100 pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#15803D] text-white">
                <FileText className="h-4 w-4" />
              </div>
              <span className="text-sm font-black text-[#1F2421]">SwasthAI Health Report</span>
            </div>
            <span
              className={`rounded-full px-2.5 py-0.5 text-[10px] font-bold ${
                report.overallStatus === 'normal'
                  ? 'bg-green-100 text-green-800'
                  : 'bg-amber-100 text-amber-800'
              }`}
            >
              {report.overallStatus.toUpperCase()}
            </span>
          </div>

          <div className="mt-3 grid grid-cols-2 gap-2 text-[11px] text-gray-600">
            <div>
              <span className="text-gray-400">Patient:</span>{' '}
              <strong className="text-gray-900">{report.userName}</strong> ({report.age}y,{' '}
              {report.sex})
            </div>
            <div className="text-right">
              <span className="text-gray-400">Report Date:</span>{' '}
              {new Date(report.createdAt).toLocaleDateString()}
            </div>
          </div>
        </div>

        {/* Regulatory Disclaimer Banner */}
        <div className="rounded-2xl bg-amber-50/80 p-3 text-[11px] leading-relaxed text-amber-950 border border-amber-200">
          <p className="font-bold">Medical Screening Disclaimer:</p>
          <p className="mt-0.5 text-amber-900">
            {report.disclaimer} SpO₂ and sensor measurements are software estimation prototypes and must be verified with certified laboratory equipment.
          </p>
        </div>

        {/* Executive Summary */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500">
            Executive Summary
          </h2>
          <p className="mt-1 text-xs text-gray-700 leading-relaxed bg-[#FAF9F6] p-3 rounded-xl border border-gray-200">
            {report.executiveSummary}
          </p>
        </div>

        {/* Vital Signs Table */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">
            Physiological Parameters & Signals
          </h2>
          <div className="overflow-hidden rounded-2xl border border-gray-200 text-xs">
            <table className="w-full text-left">
              <thead className="bg-[#FAF9F6] text-[10px] uppercase text-gray-500 border-b border-gray-200">
                <tr>
                  <th className="p-2.5 font-bold">Metric</th>
                  <th className="p-2.5 font-bold">Value</th>
                  <th className="p-2.5 font-bold">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 font-medium text-gray-800">
                <tr>
                  <td className="p-2.5">Resting Heart Rate</td>
                  <td className="p-2.5 font-bold">{report.vitals.heartRate !== null && report.vitals.heartRate !== undefined ? `${report.vitals.heartRate} BPM` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.heartRateStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Heart Rate Variability (RMSSD)</td>
                  <td className="p-2.5 font-bold">{report.vitals.hrvRmssd !== null && report.vitals.hrvRmssd !== undefined ? `${report.vitals.hrvRmssd} ms` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.hrvStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Estimated SpO₂ (Proxy)</td>
                  <td className="p-2.5 font-bold">~{report.vitals.estimatedSpO2}%</td>
                  <td className="p-2.5 text-gray-500">Prototype</td>
                </tr>
                <tr>
                  <td className="p-2.5">Weight / BMI</td>
                  <td className="p-2.5 font-bold">{report.vitals.bmi !== null && report.vitals.bmi !== undefined ? `${report.vitals.weightKg} kg (BMI ${report.vitals.bmi})` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.bmi !== null ? 'Healthy range' : 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Gait Walking Cadence</td>
                  <td className="p-2.5 font-bold">{report.vitals.cadence !== null && report.vitals.cadence !== undefined ? `${report.vitals.cadence} steps/min` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.gaitStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Acoustic Heart Sound</td>
                  <td className="p-2.5 capitalize">{report.vitals.heartSoundPattern ? report.vitals.heartSoundPattern.replace(/_/g, ' ') : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.heartSoundStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Acoustic Cough Screening</td>
                  <td className="p-2.5 capitalize">{report.vitals.coughPattern ? report.vitals.coughPattern.replace(/_/g, ' ') : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.coughStatus || 'not_tested'}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Action Items */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-1.5">
            Recommended Action Items
          </h2>
          <div className="space-y-1.5 text-xs text-gray-700">
            {report.actionItems.map((item, idx) => (
              <div key={idx} className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-[#15803D] shrink-0 mt-0.5" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Print / Download Button */}
        <button
          onClick={downloadPdf}
          disabled={isGeneratingPdf}
          className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#15803D] py-3.5 px-6 text-sm font-bold text-white shadow hover:bg-[#166534] transition-all"
        >
          <Printer className="h-4 w-4" />
          <span>Save Printable PDF for Physician</span>
        </button>
      </div>
    </div>
  );
};
