import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Share2,
  CheckCircle2,
  AlertTriangle,
  Info,
  ArrowLeft,
  ShieldCheck,
  Calendar,
  Sparkles,
  Printer
} from 'lucide-react';
import jsPDF from 'jspdf';
import { reportApi } from '../services/api';
import { HealthReport } from '../types';
import { formatReportConfidence } from '../utils/confidence';

interface Props {
  onBack?: () => void;
  onConsultDoctor?: () => void;
  onBookLab?: () => void;
}

const drawPdfTextWrapped = (
  doc: jsPDF,
  text: string,
  x: number,
  startY: number,
  maxWidth: number,
  lineHeight: number = 4.5
): number => {
  if (!text) return startY;

  const normalized = String(text).replace(/\s+/g, ' ').trim();
  if (!normalized) return startY;

  if (typeof (doc as any).setCharSpace === 'function') {
    (doc as any).setCharSpace(0);
  }
  if (typeof (doc as any).setWordSpacing === 'function') {
    (doc as any).setWordSpacing(0);
  }

  const words = normalized.split(' ');
  let currentLine = '';
  let y = startY;

  const printLine = (lineStr: string) => {
    if (y + lineHeight > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(lineStr, x, y);
  };

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const candidate = currentLine.length === 0 ? word : `${currentLine} ${word}`;

    if (doc.getTextWidth(candidate) <= maxWidth) {
      currentLine = candidate;
    } else {
      if (currentLine) {
        printLine(currentLine);
        y += lineHeight;
      }
      currentLine = word;
    }
  }

  if (currentLine) {
    printLine(currentLine);
    y += lineHeight;
  }

  return y;
};

export const ReportsScreen: React.FC<Props> = ({ onBack, onConsultDoctor, onBookLab }) => {
  const [report, setReport] = useState<HealthReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [shimmerActive, setShimmerActive] = useState(true);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    try {
      const res = await reportApi.getLatest();
      setReport(res.report);
    } catch (e) {
      console.warn('Failed to load report', e);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadPdf = () => {
    if (!report) return;
    setIsGeneratingPdf(true);
    setPdfError(null);
    setShimmerActive(false);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      if (typeof (doc as any).setCharSpace === 'function') {
        (doc as any).setCharSpace(0);
      }
      if (typeof (doc as any).setWordSpacing === 'function') {
        (doc as any).setWordSpacing(0);
      }

      // Colors
      const darkText = [31, 36, 33];

      // Header Banner
      doc.setFillColor(21, 128, 61);
      doc.rect(0, 0, 210, 24, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('SwasthSense - Personal Health Screening Report', 14, 15);

      // Metadata
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Patient: ${report.userName} | Age: ${report.age} | Sex: ${report.sex}`, 14, 32);
      doc.text(`Generated: ${new Date(report.createdAt).toLocaleString()} | Report ID: ${report.id}`, 14, 38);

      // Disclaimer Box
      doc.setDrawColor(245, 158, 11);
      doc.setFillColor(254, 243, 199);
      doc.roundedRect(14, 43, 182, 16, 2, 2, 'FD');
      doc.setFontSize(8);
      doc.setTextColor(146, 64, 14);

      const disclaimerText = 'CLINICAL NOTICE: This report is generated by a non-invasive smartphone screening system. It provides physiological monitoring and trend analysis. It is NOT a clinical diagnosis or medical device certification.';
      drawPdfTextWrapped(doc, disclaimerText, 17, 48, 176, 4);

      let y = 67;

      const checkPageBreak = (neededHeight: number) => {
        if (y + neededHeight > 275) {
          doc.addPage();
          y = 20;
        }
      };

      // 1. Executive Summary
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      doc.text('1. Executive Screening Assessment', 14, y);
      y += 6;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      const displayConfidence = formatReportConfidence(report.confidenceScore);
      doc.text(`Overall Status: ${report.overallStatus.toUpperCase()}`, 14, y);
      y += 5;
      doc.text(`Confidence Score: ${displayConfidence}%`, 14, y);
      y += 6;

      const newY = drawPdfTextWrapped(doc, report.executiveSummary, 14, y, 182, 4.5);
      y = newY + 6;

      // 2. Measured Vital Signs Table
      checkPageBreak(30);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      doc.text('2. Quantitative Vital Signs & Sensor Screening', 14, y);
      y += 6;

      doc.setFillColor(243, 244, 246);
      doc.rect(14, y, 182, 7, 'F');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('PARAMETER', 17, y + 5);
      doc.text('RECORDED VALUE', 85, y + 5);
      doc.text('SCREENING STATUS', 145, y + 5);
      y += 7;

      doc.setFont('helvetica', 'normal');
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      const tableRows = (report.modules && report.modules.length > 0)
        ? report.modules.map(m => [
            m.name.length > 34 ? m.name.substring(0, 34) + '...' : m.name,
            m.tested ? m.valueDisplay : 'Not Tested',
            m.tested ? (m.healthStatus ? m.healthStatus.toUpperCase() : 'NORMAL') : 'NOT TESTED'
          ])
        : [
            ['Resting Heart Rate (PPG)', report.vitals.heartRate !== null && report.vitals.heartRate !== undefined ? `${report.vitals.heartRate} BPM` : 'Not Tested', report.vitals.heartRateStatus ? report.vitals.heartRateStatus.toUpperCase() : 'NOT TESTED'],
            ['Heart Rate Variability (RMSSD)', report.vitals.hrvRmssd !== null && report.vitals.hrvRmssd !== undefined ? `${report.vitals.hrvRmssd} ms` : 'Not Tested', report.vitals.hrvStatus ? report.vitals.hrvStatus.toUpperCase() : 'NOT TESTED'],
            ['Estimated SpO2 (Proxy)', report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? `~${report.vitals.estimatedSpO2}%` : 'Not Tested', report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? (report.vitals.estimatedSpO2 >= 94 ? 'NORMAL' : 'FOLLOW_UP') : 'NOT TESTED'],
            ['Weight / Body Mass Index', report.vitals.bmi !== null && report.vitals.bmi !== undefined ? `${report.vitals.weightKg} kg (BMI: ${report.vitals.bmi})` : 'Not Tested', report.vitals.bmi !== null ? 'NORMAL' : 'NOT TESTED'],
            ['Walking Cadence (Gait)', report.vitals.cadence !== null && report.vitals.cadence !== undefined ? `${report.vitals.cadence} steps/min` : 'Not Tested', report.vitals.gaitStatus ? report.vitals.gaitStatus.toUpperCase() : 'NOT TESTED'],
            ['Acoustic Heart Sound Rhythm', report.vitals.heartSoundPattern ? report.vitals.heartSoundPattern.replace(/_/g, ' ') : 'Not Tested', report.vitals.heartSoundStatus ? report.vitals.heartSoundStatus.toUpperCase() : 'NOT TESTED'],
            ['Acoustic Respiratory / Cough', report.vitals.coughPattern ? report.vitals.coughPattern.replace(/_/g, ' ') : 'Not Tested', report.vitals.coughStatus ? report.vitals.coughStatus.toUpperCase() : 'NOT TESTED']
          ];

      tableRows.forEach(row => {
        checkPageBreak(8);
        doc.text(row[0], 17, y + 5);
        doc.text(row[1], 85, y + 5);
        doc.text(row[2], 145, y + 5);
        doc.setDrawColor(229, 231, 235);
        doc.line(14, y + 7, 196, y + 7);
        y += 7;
      });

      // 3. Clinical Action Items
      y += 6;
      checkPageBreak(20);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(darkText[0], darkText[1], darkText[2]);
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      doc.text('3. Physician Discussion Recommendations', 14, y);
      y += 6;

      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      if (typeof (doc as any).setCharSpace === 'function') (doc as any).setCharSpace(0);
      report.actionItems.forEach(item => {
        const itemText = String(item).replace(/\s+/g, ' ').trim();
        if (!itemText) return;

        if (y + 5 > 275) {
          doc.addPage();
          y = 20;
        }

        doc.text('•', 14, y);
        y = drawPdfTextWrapped(doc, itemText, 18, y, 178, 4.5) + 1.5;
      });

      // Save PDF file
      const fileName = `SwasthSense_Health_Report_${report.reportNumber || report.id}.pdf`;
      doc.save(fileName);
    } catch (err: any) {
      console.error(err);
      setPdfError(err.message || 'Unable to generate PDF report in this browser environment.');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  if (isLoading || !report) {
    return (
      <div className="mx-auto max-w-lg p-8 text-center text-xs text-gray-500">
        Loading latest health assessment report...
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-lg space-y-4 p-4 pb-24 animate-fade-in">
      {pdfError && (
        <div className="rounded-xl bg-red-50 p-2.5 text-xs text-red-700 border border-red-200">
          {pdfError}
        </div>
      )}

      {/* Top Header */}
      <div className="flex items-center justify-between">
        {onBack ? (
          <button
            onClick={onBack}
            className="flex items-center gap-1 text-xs font-semibold text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back</span>
          </button>
        ) : (
          <div />
        )}

        <button
          onClick={downloadPdf}
          disabled={isGeneratingPdf}
          className={`flex items-center gap-1.5 rounded-xl bg-[#15803D] px-3.5 py-1.5 text-xs font-bold text-white shadow hover:bg-[#166534] transition-all disabled:opacity-50 ${shimmerActive ? 'swasth-shimmer' : ''}`}
        >
          <Download className="h-3.5 w-3.5" />
          <span>{isGeneratingPdf ? 'Exporting...' : 'Download PDF'}</span>
        </button>
      </div>

      {/* Structured Health Report Preview */}
      <div className="rounded-3xl border border-[#EAE7DE] bg-white p-6 shadow-xs space-y-5">
        {/* Document Header */}
        <div className="border-b border-gray-100 pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#15803D] text-white">
                <FileText className="h-4 w-4" />
              </div>
              <span className="text-sm font-black text-[#1F2421]">SwasthSense Health Report</span>
            </div>
            <span
              className={`rounded-full px-2.5 py-0.5 text-[10px] font-bold ${
                report.overallStatus === 'normal'
                  ? 'bg-green-100 text-green-800'
                  : 'bg-amber-100 text-amber-800'
              }`}
            >
              {report.overallStatus.toUpperCase()}
            </span>
          </div>

          <div className="mt-3 grid grid-cols-2 gap-2 text-[11px] text-gray-600">
            <div>
              <span className="text-gray-400">Patient:</span>{' '}
              <strong className="text-gray-900">{report.userName}</strong> ({report.age}y,{' '}
              {report.sex})
            </div>
            <div className="text-right">
              <span className="text-gray-400">Report Date:</span>{' '}
              {new Date(report.createdAt).toLocaleDateString()}
            </div>
          </div>
        </div>

        {/* Regulatory Disclaimer Banner */}
        <div className="rounded-2xl bg-amber-50/80 p-3 text-[11px] leading-relaxed text-amber-950 border border-amber-200">
          <p className="font-bold">Medical Screening Disclaimer:</p>
          <p className="mt-0.5 text-amber-900">
            {report.disclaimer} SpO₂ and sensor measurements are software estimation prototypes and must be verified with certified laboratory equipment.
          </p>
        </div>

        {/* Executive Summary */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500">
            Executive Summary
          </h2>
          <p className="mt-1 text-xs text-gray-700 leading-relaxed bg-[#FAF9F6] p-3 rounded-xl border border-gray-200">
            {report.executiveSummary}
          </p>
        </div>

        {/* Vital Signs Table */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">
            Physiological Parameters & Signals
          </h2>
          <div className="overflow-hidden rounded-2xl border border-gray-200 text-xs">
            <table className="w-full text-left">
              <thead className="bg-[#FAF9F6] text-[10px] uppercase text-gray-500 border-b border-gray-200">
                <tr>
                  <th className="p-2.5 font-bold">Metric</th>
                  <th className="p-2.5 font-bold">Value</th>
                  <th className="p-2.5 font-bold">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 font-medium text-gray-800">
                <tr>
                  <td className="p-2.5">Resting Heart Rate</td>
                  <td className="p-2.5 font-bold">{report.vitals.heartRate !== null && report.vitals.heartRate !== undefined ? `${report.vitals.heartRate} BPM` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.heartRateStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Heart Rate Variability (RMSSD)</td>
                  <td className="p-2.5 font-bold">{report.vitals.hrvRmssd !== null && report.vitals.hrvRmssd !== undefined ? `${report.vitals.hrvRmssd} ms` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.hrvStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Estimated SpO₂ (Proxy)</td>
                  <td className="p-2.5 font-bold">{report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? `~${report.vitals.estimatedSpO2}%` : 'Not Tested'}</td>
                  <td className={`p-2.5 font-bold capitalize ${report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? (report.vitals.estimatedSpO2 >= 94 ? 'text-green-700' : 'text-red-700') : 'text-gray-400'}`}>
                    {report.vitals.estimatedSpO2 !== null && report.vitals.estimatedSpO2 !== undefined ? (report.vitals.estimatedSpO2 >= 94 ? 'normal' : 'follow_up') : 'not_tested'}
                  </td>
                </tr>
                <tr>
                  <td className="p-2.5">Weight / BMI</td>
                  <td className="p-2.5 font-bold">{report.vitals.bmi !== null && report.vitals.bmi !== undefined ? `${report.vitals.weightKg} kg (BMI ${report.vitals.bmi})` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.bmi !== null ? 'Healthy range' : 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Gait Walking Cadence</td>
                  <td className="p-2.5 font-bold">{report.vitals.cadence !== null && report.vitals.cadence !== undefined ? `${report.vitals.cadence} steps/min` : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.gaitStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Acoustic Heart Sound</td>
                  <td className="p-2.5 capitalize">{report.vitals.heartSoundPattern ? report.vitals.heartSoundPattern.replace(/_/g, ' ') : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.heartSoundStatus || 'not_tested'}</td>
                </tr>
                <tr>
                  <td className="p-2.5">Acoustic Cough Screening</td>
                  <td className="p-2.5 capitalize">{report.vitals.coughPattern ? report.vitals.coughPattern.replace(/_/g, ' ') : 'Not Tested'}</td>
                  <td className="p-2.5 text-green-700 capitalize">{report.vitals.coughStatus || 'not_tested'}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Action Items */}
        <div>
          <h2 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-1.5">
            Recommended Action Items
          </h2>
          <div className="space-y-1.5 text-xs text-gray-700">
            {report.actionItems.map((item, idx) => (
              <div key={idx} className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-[#15803D] shrink-0 mt-0.5" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Print / Download Button */}
        <button
          onClick={downloadPdf}
          disabled={isGeneratingPdf}
          className={`flex w-full items-center justify-center gap-2 rounded-2xl bg-[#15803D] py-3.5 px-6 text-sm font-bold text-white shadow hover:bg-[#166534] transition-all ${shimmerActive ? 'swasth-shimmer' : ''}`}
        >
          <Printer className="h-4 w-4" />
          <span>Save Printable PDF for Physician</span>
        </button>
      </div>
    </div>
  );
};
